server:
  port: 9001
page:
  size: 5

spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
 profiles:
   active: dev
 application:
   name: user-service
 #读取到
#mybatis
mybatis:
  type-aliases-package: com.lanou.model
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.lanou.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql